const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Plugins.Audio,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.AddVar
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{fundo: 0},
	{play: 0},
	{Sólido: 0},
	{chao: 0},
	{Projétil: 0},
	{cobra: 0},
	{moeda: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{player: 0},
	{Teclado: 0},
	{Partículas: 0},
	{PartículasMoeda: 0},
	{PartículasMorte: 0},
	{Sprite: 0},
	{Texto: 0},
	{Áudio: 0},
	{chao_quebra: 0},
	{Sprite2: 0},
	{pontos: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	fundo: class extends self.ISpriteInstance {},
	play: class extends self.ISpriteInstance {},
	chao: class extends self.ITiledBackgroundInstance {},
	cobra: class extends self.ISpriteInstance {},
	moeda: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Partículas: class extends self.IParticlesInstance {},
	PartículasMoeda: class extends self.IParticlesInstance {},
	PartículasMorte: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Texto: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	chao_quebra: class extends self.ITiledBackgroundInstance {},
	Sprite2: class extends self.ISpriteInstance {}
}